name: Trigger auto deployment for container-app-633iowbjmdfg6

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'fastify-api-server/**'
    - '.github/workflows/container-app-633iowbjmdfg6-AutoDeployTrigger-97b0437b-c124-4caf-b41c-5812f0cc0c1f.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPP633IOWBJMDFG6_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPP633IOWBJMDFG6_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPP633IOWBJMDFG6_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/fastify-api-server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPP633IOWBJMDFG6_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPP633IOWBJMDFG6_REGISTRY_PASSWORD }}
          containerAppName: container-app-633iowbjmdfg6
          resourceGroup: shopathomesampleb9f2
          imageToBuild: default/container-app-633iowbjmdfg6:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


